name: logging_bugfender
description: A library helping integrate Bugfender with the logging package.
version: 5.0.0
homepage: https://github.com/leancodepl/logging_bugfender

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter_bugfender: ^4.0.0
  logging: ^1.0.2

dev_dependencies:
  leancode_lint: '>=2.1.0 <2.2.0'
